### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by xieruopeng** [aezarebski/timtam2#24]
Can you kindly give a detailed description for the folders under doc/Vigettes?

What scenarios are these examples applicable to？

Thanks.

**Comment by aezarebski** [comment]
Hi @xieruopeng 

Thank you for pointing this out. 

At the moment I'm implementing time varying parameters (see the `skyline` branch) so the organisation of the code/vignettes will change soon and there may be breaking changes to the API so I would not advise using this "in production" unless you take care to note the exact commit you are using.

You're right, the layout is a bit confusing, I'll keep this in mind during the re-organisation and add some comments about intended use-cases. Currently, they are organised by the type of data (do you have scheduled or unscheduled sampling) and whether or not you want to estimate the tree (or just the rates and prevalence).

I'll leave this open as a reminder. If you have any further questions or suggestions, please let me know.

Cheers,
Alex

**Comment by xieruopeng** [comment]
Thanks for your reply. 

Actually I read your paper in which you mentioned
