### ISSUE TITLE
Tutorial 3: prevalence curve

### ISSUE THREAD

**Issue by xieruopeng** [aezarebski/timtam2#42]
Dear Alex,

In tutorial 3, the log file just shows prevalence at the time of the last observation. Is it possible to show prevalence curve over time like birthRate?

Many thanks in advance!

Cheers,
Ruopeng

**Comment by aezarebski** [comment]
Hi Ruopeng,

The current method does not have a way to estimate the prevalence through time. There are a couple of approaches that could work, but they all require non-trivial changes to the package.

If you are in a rush for any estimate, you could generate a *rough* estimate of the prevalence at time `T` by only using the data from before then, and then do this for a couple of different times.

I hope the tutorials have been helpful, please let me know if you have any feedback/suggestions.

Cheers,
Alex

**Comment by xieruopeng** [comment]
Thanks Alex!

**Comment by aezarebski** [comment]
Hey @xieruopeng 

Just wanted to let you know that historical prevalence estimation is now implemented on the `dev` branch so will hopefully appear in `v.0.3.0`. It appears to work on a simple example (included in `examples/ex4.xml`) but BEAUti support is pretty rubbish and there isn't any proper documentation on it yet, so it might be a while.

Cheers,
Alex

**Comment by aezarebski** [comment]
There is now a pre-release with this implemented so I'll close the issue :)
